---
title: "Are we SMART?"
description: |
output:
  distill::distill_article:
    self_contained: false
---


## SMART criteria

Our solution meets the SMART criteria in the following ways:

### 'S’ (specific) = Does the solution you deliver match with the specific challenge of the Hackathon? Is it clear enough from your entry for the judges to assess you have completed a solution?

Our solution seeks to help the public to understand when they are about to move into a district (e.g. a weekend trip to another county) or time period (e.g. a weekend where parks are likely to be very busy) where there may be a higher risk of COVID-19 transmission due to the busyness of parks. 
The defaults of our app are set to display this information for Bedford. The default screen shows:
The historical park visiting trends for Bedford alongside the forecasted busyness (grey bars for less bust than winter, green bars for more busy than winter) based on OpenWeather forecasts and on weather, park usage and access to green space data (white bar)
Bedford highlighted within a chloropleth map of park busyness across England (darker shades of green for more busy than winter, white for neutral, grey for less busy than winter).
These graphics allow Bedfordians to visualise how the busyness of parks has changed over time in their Bedford and experimentally forecast how busy it is likely to be in the next few days. It also places the busyness of Bedford’s parks within the wider context of the busyness of parks in other regions of England. Users can select other regions and days of the week to explore other regions’ data further.

### ‘M’ (measurable) = Does the digital solution you put forward permit a ‘measurable outcome’? Does your entry meet expectations?

Our measurable outcome is an app that allows the public to understand park busyness trends over the pandemic and experimentally forecast how parks in their area are likely to be in the future, according to the historical and forecast weather data, and social science data. Behind the forecasting element is complex modelling based on multiple sources the bringing together of big data, environmental and social science data, but we are able to reduce this complexity to a simple metric that is intuitive to users - a forecast of park busyness.

### ‘A’ (achievable) = Is the digital solution put forward sensible and practical? Was the solution achieved within the time frame, opportunity and resources?

We believe our solution is a sensible yet innovative use of environmental data for aiding the understanding risk in the COVID-19 pandemic. The increased popularity of parks during the COVID-19 pandemic makes them a potential hotspot for COVID-19 transmission, and the public have to manage this health risk with the risk of not visiting parks on their physical and mental health. We know that park usage is related to the weather and social factors, and so we thought it natural to combine these data to develop an experimental forecast of park busyness to help users understand potential risks associated with park visits during the pandemic.
We have assembled a new team with diverse expertise and brought together several sources of open data to achieve this. We have grabbed the opportunity of the availability of new datasets in the pandemic as well as incorporating more established datasets (e.g. Natural England, Office for National Statistics data). We are proud of the experimental app we have created in just 4 weeks!

### ‘R’ (relevant) = Does the digital solution put forward have scientific merit (in NERC remit), with relevance to the overall Hackathon theme? Does the digital solution have the desired impact?

Our solution covers the NERC remit well. It uses atmospheric/earth observation  data to understand the physical processes acting upon life - in this case, humans! Additionally, we are truly interdisciplinary in that we use social science-type data from Natural England and the Office for National Statistics relating to greenspace usage and access. It addresses key societal challenges; most obviously, helping individuals and organisations to understand the potential risk of COVID-19 transmission in busy parks. Less obviously though, the increased use of parks during the pandemic presents other environmental challenges such as ‘flash’ littering, footpath erosion and other environmental damage - all of which need to be managed and preferably, predicted in advance. Our experimental forecast uses environmental and social science data to explore the viability of this approach using the Google data as a starting point. Although Google data should be used with caution and Google state ‘This dataset is intended to help remediate the impact of COVID-19. It shouldn’t be used for medical diagnostic, prognostic, or treatment purposes. It also isn’t intended to be used for guidance on personal travel plans.’, this app provides a proof-of-principle for this approach when datasets about ongoing park usage are made available for applied usage. When these datasets are made available for this purpose, it could allow society (e.g. Bedfordians planning weekend trips to Cornwall), the government (e.g. Public Health England, Natural England, the Environment Agency), businesses (e.g.outdoor recreation and retail businesses).
More generally, the combined dataset we have pieced together from multiple different datasets presents a new opportunity and proof-of-principle for pure, applied and/or policy-driven work. In line with the Challenge, we have emphasised the latter two types of work - but there are also ample opportunities for pure environmental science here. Essentially, we have created an exciting new dataset could act as the basis for understanding the movement ecology of humans based on environmental and social factors and/or be used to understand how humans’ use of greenspaces is likely to impact the ecology of plants and animals.

### ‘T’ (timebound) = Has the topic been adequately addressed satisfactorily within the allocated weeks?

We believe that given the time constraints, we have made significant progress towards the goal of building a proof-of-principle forecasting system for park busyness based on environmental and social science data. In 4 weeks:

* All the datasets we aimed to bring together and more have been brought together - including Google data, Met Office data, Natural England, Office for National Statistics and OpenWeather forecast data

* We have visualised the Google data and our predictions of it in the more intuitive formats of a bar graph and a map. These are fully interactive so that users can view a particular time period in the pandemic and the bar graph and map will change, facilitating the understanding of historical changes.

* We have produced an experimental forecast of future park busyness based on weather and social science data, and displayed this alongside the historical Google data.The forecasting model parameters will be refined in the future to improve predictions, and if made available, used with non-Google data intended for more applied usage. Nonetheless, the platform to visualise these forecasts is already there!

